const fs = require('fs');
const path = require('path');
const vscode = require('vscode');
const LgdFixGlob = require('./LgdFixGlob');
const createQuickFixRegistry = require('../QuickFixes/QuickFixRegistry');

/** @description Configuration inheritance is deliberately bounded in both depth and total reads. */
const limits = { bytes: 262144, depth: 10, configs: 100, patterns: 256, overrides: 100, parents: 32, pathLength: 512 };

/** @description Files generated by tools and parser regression fixtures are never fix targets. */
const excludedDirectories = new Set([ 'node_modules', '.git', 'dist', 'build', 'coverage', 'vendor', 'generated', 'typings' ]);

/** @description Resolves safe, declarative project fix settings without caching configuration text. */
const LgdFixConfiguration = {
    /**
     * @description Creates an independent configuration reader and diagnostic collection.
     * @param {Array<string>} [ruleIds] known rule identifiers from the fix registry.
     * @returns {Object} the configuration reader.
     */
    create(ruleIds)
    {
        const reader = Object.create(this);
        const registeredIds = ruleIds || Array.from(createQuickFixRegistry().values(), handler => handler.ruleId);
        reader.ruleIds = new Set(registeredIds);
        reader.diagnostics = vscode.languages.createDiagnosticCollection?.('lgd-fix-configuration');
        reader.trackedPaths = new Set();
        reader.disposed = false;
        return reader;
    },

    /**
     * @description Resolves the nearest project configuration, failing closed on any invalid setting.
     * @param {Object} document the target source document.
     * @returns {Promise<Object>} effective fix settings and their input snapshots.
     */
    async resolve(document)
    {
        const result = { valid: true, ignored: false, autoFix: false, rules: {}, root: null, configPath: null, workspaceRoot: null, configSnapshots: [] };
        if(document.uri.scheme !== 'file')
        {
            return result;
        }

        const sourcePath = path.resolve(document.uri.fsPath);
        result.ignored = this._isHardExcluded(sourcePath);
        const folder = vscode.workspace.getWorkspaceFolder?.(document.uri);
        if(!folder || folder.uri.scheme !== 'file')
        {
            return result;
        }

        const workspaceRoot = path.resolve(folder.uri.fsPath);
        result.root = workspaceRoot;
        result.workspaceRoot = workspaceRoot;
        result.ignored = this._isHardExcluded(path.relative(workspaceRoot, sourcePath));
        let configPath;
        try
        {
            if(!this._isInside(workspaceRoot, sourcePath))
            {
                throw new Error('The source file is outside its workspace folder.');
            }

            const realWorkspace = await fs.promises.realpath(workspaceRoot);
            result.sourceRealPath = await this._realPath(sourcePath);
            if(!this._isInside(realWorkspace, result.sourceRealPath))
            {
                throw new Error('The source file resolves outside its workspace folder.');
            }

            result.ignored ||= this._isHardExcluded(path.relative(realWorkspace, result.sourceRealPath));
            const context = { workspaceRoot: workspaceRoot, realWorkspace: realWorkspace, snapshots: result.configSnapshots, stack: new Set() };
            let directory = path.dirname(sourcePath);
            while(this._isInside(workspaceRoot, directory))
            {
                const candidate = path.join(directory, '.vscode', 'lgd.json');
                const snapshot = await this._readSnapshot(candidate, context);
                if(snapshot.text !== null)
                {
                    configPath = candidate;
                    result.configPath = candidate;
                    result.root = directory;
                    const layers = await this._load(snapshot, context);
                    this._applyLayers(result, layers, path.relative(directory, sourcePath).split(path.sep).join('/'));
                    break;
                }

                if(directory === workspaceRoot)
                {
                    break;
                }

                directory = path.dirname(directory);
            }
        }
        catch(error)
        {
            result.valid = false;
            result.autoFix = false;
            result.rules = {};
            const failedPath = error.configurationPath || configPath;
            if(failedPath)
            {
                this._reportError(failedPath, error.message);
            }
        }

        return result;
    },

    /**
     * @description Re-reads configuration before edits, including missing nearer configurations and dirty buffers.
     * @param {Object} document the target source document.
     * @param {Object} resolution the earlier resolved settings.
     * @returns {Promise<boolean>} whether the configuration inputs are unchanged and still valid.
     */
    async isCurrent(document, resolution)
    {
        if(!resolution.valid || this.disposed)
        {
            return false;
        }

        const current = await this.resolve(document);
        return current.valid && JSON.stringify(current) === JSON.stringify(resolution) && this.buffersCurrent(resolution);
    },

    /**
     * @description Checks every config buffer synchronously after asynchronous batch checks and immediately before edits.
     * @param {Object} resolution the earlier resolved settings.
     * @returns {boolean} whether open, closed, edited, and newly created config buffers still match.
     */
    buffersCurrent(resolution)
    {
        if(!resolution.valid || this.disposed)
        {
            return false;
        }

        return resolution.configSnapshots.every(snapshot =>
        {
            const document = this._openDocument(snapshot.path);
            if(Boolean(document) !== snapshot.open)
            {
                return false;
            }

            return !document || document.getText() === snapshot.text && (document.version ?? null) === snapshot.version;
        });
    },

    /**
     * @description Registers only configuration-diagnostic refreshes; configuration changes never edit source files.
     * @param {Array<Object>} subscriptions extension subscriptions that own these listeners.
     */
    register(subscriptions)
    {
        subscriptions.push(this);
        const refresh = async () =>
        {
            await this._refreshDiagnostics();
        };

        const refreshDocument = async event =>
        {
            const document = event.document || event;
            if(this._isTrackedConfiguration(document.uri))
            {
                this.diagnostics?.delete(document.uri);
                await this._refreshDiagnostics();
            }
        };

        const refreshFile = async uri =>
        {
            if(this._isTrackedConfiguration(uri))
            {
                this.diagnostics?.delete(uri);
                await this._refreshDiagnostics();
            }
        };

        if(vscode.workspace.onDidChangeTextDocument)
        {
            subscriptions.push(vscode.workspace.onDidChangeTextDocument(refreshDocument));
            subscriptions.push(vscode.workspace.onDidOpenTextDocument(refreshDocument));
            subscriptions.push(vscode.workspace.onDidCloseTextDocument(refreshDocument));
        }

        if(vscode.workspace.createFileSystemWatcher)
        {
            const watcher = vscode.workspace.createFileSystemWatcher('**/*.json');
            subscriptions.push(watcher, watcher.onDidChange(refreshFile), watcher.onDidCreate(refreshFile), watcher.onDidDelete(refreshFile));
        }

        if(vscode.workspace.onDidChangeWorkspaceFolders)
        {
            subscriptions.push(vscode.workspace.onDidChangeWorkspaceFolders(refresh));
        }

        return this._refreshDiagnostics();
    },

    /** @description Disposes diagnostics together with the extension's configuration listeners. */
    dispose()
    {
        this.disposed = true;
        this.diagnostics?.dispose();
        this.trackedPaths.clear();
    },

    _isInside(root, target)
    {
        const relative = path.relative(root, target);
        return relative === '' || relative !== '..' && !relative.startsWith(`..${path.sep}`) && !path.isAbsolute(relative);
    },

    async _realPath(target)
    {
        try
        {
            return await fs.promises.realpath(target);
        }
        catch(error)
        {
            if(error.code !== 'ENOENT' && error.code !== 'ENOTDIR')
            {
                throw error;
            }

            const parent = path.dirname(target);
            if(parent === target)
            {
                throw error;
            }

            return path.join(await this._realPath(parent), path.basename(target));
        }
    },

    _isHardExcluded(sourcePath)
    {
        const segments = sourcePath.toLowerCase().split(path.sep);
        if(segments.some(segment => excludedDirectories.has(segment)))
        {
            return true;
        }

        const fixture = segments.some((segment, index) => segment === 'tests' && [ 'mocks', '__mocks__' ].includes(segments[index + 1]));
        return fixture || sourcePath.toLowerCase().endsWith('.generated.lgd') || (/\.d\.(?:ts|cts|mts)$/i).test(sourcePath);
    },

    _openDocument(configPath)
    {
        return (vscode.workspace.textDocuments || []).find(document => !document.isClosed && document.uri.scheme === 'file' && path.resolve(document.uri.fsPath) === configPath);
    },

    async _readSnapshot(configPath, context)
    {
        try
        {
            if(!this._isInside(context.workspaceRoot, configPath))
            {
                throw new Error('Extended configuration must remain inside the workspace folder.');
            }

            const realPath = await this._realPath(configPath);
            if(!this._isInside(context.realWorkspace, realPath))
            {
                throw new Error('Configuration symlinks must remain inside the workspace folder.');
            }

            let text = null;
            let document = this._openDocument(configPath);
            if(!document)
            {
                try
                {
                    const stat = await fs.promises.stat(realPath);
                    if(!stat.isFile() || stat.size > limits.bytes)
                    {
                        throw new Error('LGD configuration must be a JSON file no larger than 256 KiB.');
                    }

                    text = await fs.promises.readFile(realPath, 'utf8');
                }
                catch(error)
                {
                    if(error.code !== 'ENOENT')
                    {
                        throw error;
                    }
                }

                document = this._openDocument(configPath);
            }

            let version = null;
            if(document)
            {
                text = document.getText();
                version = document.version ?? null;
            }

            if(text !== null && Buffer.byteLength(text, 'utf8') > limits.bytes)
            {
                throw new Error('LGD configuration must be no larger than 256 KiB.');
            }

            const snapshot = { path: configPath, realPath: realPath, text: text, version: version, open: Boolean(document) };
            context.snapshots.push(snapshot);
            this.diagnostics?.delete(vscode.Uri.file(configPath));
            if(text !== null)
            {
                this.trackedPaths.add(configPath);
            }

            return snapshot;
        }
        catch(error)
        {
            error.configurationPath = configPath;
            throw error;
        }
    },

    async _load(snapshot, context)
    {
        try
        {
            if(context.stack.has(snapshot.realPath))
            {
                throw new Error('LGD configuration extends contains a cycle.');
            }

            if(context.stack.size >= limits.depth || context.snapshots.length > limits.configs)
            {
                throw new Error('LGD configuration extends exceeds the limit of 10 levels or 100 files.');
            }

            if(snapshot.text === null)
            {
                throw new Error('The extended LGD configuration file does not exist.');
            }

            let configuration;
            try
            {
                configuration = JSON.parse(snapshot.text);
            }
            catch
            {
                throw new Error('Invalid JSON in LGD configuration. Remove comments, trailing commas, and other JSON syntax errors.');
            }

            this._validate(configuration);
            context.stack.add(snapshot.realPath);
            const layers = [];
            let parents = configuration.extends || [];
            if(typeof parents === 'string')
            {
                parents = [parents];
            }

            for(const reference of parents)
            {
                const parentPath = path.resolve(path.dirname(snapshot.path), reference);
                const parentSnapshot = await this._readSnapshot(parentPath, context);
                layers.push(...await this._load(parentSnapshot, context));
            }

            context.stack.delete(snapshot.realPath);
            layers.push(configuration);
            return layers;
        }
        catch(error)
        {
            error.configurationPath ||= snapshot.path;
            throw error;
        }
    },

    _validate(configuration)
    {
        this._validateKeys(configuration, [ '$schema', 'version', 'autoFix', 'rules', 'ignores', 'overrides', 'extends' ], 'configuration');
        if(configuration.version !== 1)
        {
            throw new Error('LGD configuration requires "version": 1.');
        }

        if(configuration.$schema !== undefined && typeof configuration.$schema !== 'string')
        {
            throw new TypeError('LGD configuration $schema must be a string.');
        }

        if(configuration.autoFix !== undefined && typeof configuration.autoFix !== 'boolean')
        {
            throw new TypeError('LGD configuration autoFix must be true or false.');
        }

        this._validateRules(configuration.rules, 'rules');
        this._validatePatterns(configuration.ignores, 'ignores');
        this._validateExtends(configuration.extends);
        if(configuration.overrides === undefined)
        {
            return;
        }

        if(!Array.isArray(configuration.overrides) || configuration.overrides.length > limits.overrides)
        {
            throw new TypeError('LGD configuration overrides must be an array of at most 100 entries.');
        }

        for(const override of configuration.overrides)
        {
            this._validateKeys(override, [ 'files', 'ignores', 'rules' ], 'override');
            this._validatePatterns(override.files, 'override.files', true);
            this._validatePatterns(override.ignores, 'override.ignores');
            this._validateRules(override.rules, 'override.rules');
        }
    },

    _validateKeys(value, allowed, label)
    {
        if(!value || typeof value !== 'object' || Array.isArray(value))
        {
            throw new TypeError(`LGD ${label} must be an object.`);
        }

        for(const key of Object.keys(value))
        {
            if(!allowed.includes(key))
            {
                throw new Error(`Unknown LGD ${label} setting "${key}".`);
            }
        }
    },

    _validateRules(rules, label)
    {
        if(rules === undefined)
        {
            return;
        }

        this._validateKeys(rules, [...this.ruleIds], label);
        for(const [ ruleId, setting ] of Object.entries(rules))
        {
            this._validateKeys(setting, ['fix'], `${label}.${ruleId}`);
            if(![ 'off', 'manual', 'automatic' ].includes(setting.fix))
            {
                throw new Error(`LGD ${label}.${ruleId}.fix must be "off", "manual", or "automatic".`);
            }
        }
    },

    _validatePatterns(patterns, label, required = false)
    {
        if(patterns === undefined && !required)
        {
            return;
        }

        if(!Array.isArray(patterns) || patterns.length > limits.patterns || required && patterns.length === 0)
        {
            throw new TypeError(`LGD ${label} must be an array of at most 256 glob strings${required ? ' with at least one pattern' : ''}.`);
        }

        if(patterns.some(pattern => !LgdFixGlob.isValidPattern(pattern)))
        {
            throw new Error(`LGD ${label} accepts project-relative globs with *, ?, and full-segment ** only (maximum 512 characters).`);
        }
    },

    _validateExtends(references)
    {
        if(references === undefined)
        {
            return;
        }

        const parents = typeof references === 'string' ? [references] : references;
        if(!Array.isArray(parents) || parents.length > limits.parents)
        {
            throw new TypeError('LGD extends must be a relative JSON path or an array of at most 32 paths.');
        }

        for(const reference of parents)
        {
            const relative = typeof reference === 'string' && (reference.startsWith('./') || reference.startsWith('../'));
            if(!relative || reference.length > limits.pathLength || !reference.endsWith('.json') || (/[\p{Cc}*:?\\]/u).test(reference))
            {
                throw new Error('LGD extends accepts only relative ./ or ../ JSON paths inside the workspace folder.');
            }
        }
    },

    _applyLayers(result, layers, relativePath)
    {
        for(const layer of layers)
        {
            if(layer.autoFix !== undefined)
            {
                result.autoFix = layer.autoFix;
            }

            Object.assign(result.rules, layer.rules);
            if(layer.ignores?.some(pattern => LgdFixGlob.matches(pattern, relativePath)))
            {
                result.ignored = true;
            }

            for(const override of layer.overrides || [])
            {
                const matched = override.files.some(pattern => LgdFixGlob.matches(pattern, relativePath));
                const excluded = override.ignores?.some(pattern => LgdFixGlob.matches(pattern, relativePath));
                if(matched && !excluded)
                {
                    Object.assign(result.rules, override.rules);
                }
            }
        }
    },

    _isTrackedConfiguration(uri)
    {
        if(uri.scheme !== 'file')
        {
            return false;
        }

        const configPath = path.resolve(uri.fsPath);
        return this.trackedPaths.has(configPath) || path.basename(configPath) === 'lgd.json' && path.basename(path.dirname(configPath)) === '.vscode';
    },

    async _refreshDiagnostics()
    {
        if(this.disposed)
        {
            return;
        }

        const documents = [...vscode.workspace.textDocuments || []];
        for(const document of documents)
        {
            if(document.languageId === 'lgd')
            {
                await this.resolve(document);
            }
            else if(document.uri.scheme === 'file' && path.basename(document.uri.fsPath) === 'lgd.json' && path.basename(path.dirname(document.uri.fsPath)) === '.vscode')
            {
                const root = path.dirname(path.dirname(document.uri.fsPath));
                await this.resolve({ uri: vscode.Uri.file(path.join(root, '__lgd_configuration_check__.lgd')) });
            }
        }
    },

    _reportError(configPath, message)
    {
        if(!this.diagnostics || this.disposed)
        {
            return;
        }

        const range = new vscode.Range(new vscode.Position(0, 0), new vscode.Position(0, 1));
        const diagnostic = new vscode.Diagnostic(range, message, vscode.DiagnosticSeverity.Error);
        diagnostic.source = 'LGD configuration';
        diagnostic.code = 'lgd-fix-configuration';
        this.diagnostics.set(vscode.Uri.file(configPath), [diagnostic]);
    }
};

module.exports = LgdFixConfiguration;
