const fs = require('fs');
const path = require('path');
const vscode = require('vscode');
const LgdFixSettings = require('../../Lgd/Fixes/LgdFixSettings');
const LgdFormattingPolicy = require('../../Lgd/Fixes/LgdFormattingPolicy');
const createQuickFixRegistry = require('../../Lgd/QuickFixes/QuickFixRegistry');

/** @description Configuration inheritance is deliberately bounded in both depth and total reads. */
const limits = { bytes: 262144, depth: 10, configs: 100 };

/** @description Files generated by tools and parser regression fixtures are never fix targets. */
const excludedDirectories = new Set([ 'node_modules', '.git', 'dist', 'build', 'coverage', 'vendor', 'generated', 'typings' ]);

/** @description Resolves safe, declarative project fix settings without caching configuration text. */
const LgdFixConfiguration = {
    /**
     * @description Creates an independent configuration reader and diagnostic collection.
     * @param {Array<string>} [ruleIds] known rule identifiers from the fix registry.
     * @param {Object} [formattingSources] bounded declarative preference source resolver.
     * @returns {Object} the configuration reader.
     */
    create(ruleIds, formattingSources = null)
    {
        const reader = Object.create(this);
        const registeredIds = ruleIds || Array.from(createQuickFixRegistry().values(), handler => handler.ruleId);
        reader.ruleIds = new Set([ ...registeredIds, ...LgdFormattingPolicy.rules().map(rule => rule.id) ]);
        reader.formattingSources = formattingSources;
        reader.settings = LgdFixSettings.create(reader.ruleIds);
        reader.diagnostics = vscode.languages.createDiagnosticCollection?.('lgd-fix-configuration');
        reader.trackedPaths = new Set();
        reader.disposed = false;
        return reader;
    },

    /**
     * @description Resolves the nearest project configuration, failing closed on any invalid setting.
     * @param {Object} document the target source document.
     * @returns {Promise<Object>} effective fix settings and their input snapshots.
     */
    async resolve(document)
    {
        const result = { valid: true, ignored: false, autoFix: false, rules: {}, root: null, configPath: null, workspaceRoot: null, configSnapshots: [],
            formatting: { enabled: false, sources: LgdFormattingPolicy.sourceNames.slice(), options: {} } };
        if(document.uri.scheme !== 'file')
        {
            return result;
        }

        const sourcePath = path.resolve(document.uri.fsPath);
        result.ignored = this._isHardExcluded(sourcePath);
        const folder = vscode.workspace.getWorkspaceFolder?.(document.uri);
        if(!folder || folder.uri.scheme !== 'file')
        {
            return result;
        }

        const workspaceRoot = path.resolve(folder.uri.fsPath);
        result.root = workspaceRoot;
        result.workspaceRoot = workspaceRoot;
        result.ignored = this._isHardExcluded(path.relative(workspaceRoot, sourcePath));
        let configPath;
        try
        {
            if(!this._isInside(workspaceRoot, sourcePath))
            {
                throw new Error('The source file is outside its workspace folder.');
            }

            const realWorkspace = await fs.promises.realpath(workspaceRoot);
            result.sourceRealPath = await this._realPath(sourcePath);
            if(!this._isInside(realWorkspace, result.sourceRealPath))
            {
                throw new Error('The source file resolves outside its workspace folder.');
            }

            result.ignored ||= this._isHardExcluded(path.relative(realWorkspace, result.sourceRealPath));
            const context = { workspaceRoot: workspaceRoot, realWorkspace: realWorkspace, snapshots: result.configSnapshots, stack: new Set() };
            let directory = path.dirname(sourcePath);
            while(this._isInside(workspaceRoot, directory))
            {
                const candidate = path.join(directory, '.vscode', 'lgd.json');
                const snapshot = await this._readSnapshot(candidate, context);
                if(snapshot.text !== null)
                {
                    configPath = candidate;
                    result.configPath = candidate;
                    result.root = directory;
                    const layers = await this._load(snapshot, context);
                    this.settings.applyLayers(result, layers, path.relative(directory, sourcePath).split(path.sep).join('/'));
                    break;
                }

                if(directory === workspaceRoot)
                {
                    break;
                }

                directory = path.dirname(directory);
            }

            await this._resolveFormatting(result, context, sourcePath);
        }
        catch(error)
        {
            result.valid = false;
            result.autoFix = false;
            result.rules = {};
            const failedPath = error.configurationPath || configPath;
            if(failedPath)
            {
                this._reportError(failedPath, error.message);
            }
        }

        return result;
    },

    /**
     * @description Re-reads configuration before edits, including missing nearer configurations and dirty buffers.
     * @param {Object} document the target source document.
     * @param {Object} resolution the earlier resolved settings.
     * @returns {Promise<boolean>} whether the configuration inputs are unchanged and still valid.
     */
    async isCurrent(document, resolution)
    {
        if(!resolution.valid || this.disposed)
        {
            return false;
        }

        const current = await this.resolve(document);
        return current.valid && JSON.stringify(current) === JSON.stringify(resolution) && this.buffersCurrent(resolution);
    },

    /**
     * @description Checks every config buffer synchronously after asynchronous batch checks and immediately before edits.
     * @param {Object} resolution the earlier resolved settings.
     * @returns {boolean} whether open, closed, edited, and newly created config buffers still match.
     */
    buffersCurrent(resolution)
    {
        if(!resolution.valid || this.disposed)
        {
            return false;
        }

        return resolution.configSnapshots.every(snapshot =>
        {
            const document = this._openDocument(snapshot.path);
            if(Boolean(document) !== snapshot.open)
            {
                return false;
            }

            return !document || document.getText() === snapshot.text && (document.version ?? null) === snapshot.version;
        });
    },

    /**
     * @description Registers only configuration-diagnostic refreshes; configuration changes never edit source files.
     * @param {Array<Object>} subscriptions extension subscriptions that own these listeners.
     * @param {Function} [onChange] refreshes editor presentation after configuration changes.
     */
    register(subscriptions, onChange)
    {
        subscriptions.push(this);
        this.onChange = onChange;
        const refresh = async () =>
        {
            await this._refreshDiagnostics();
        };

        const refreshDocument = async event =>
        {
            const document = event.document || event;
            if(this._isTrackedConfiguration(document.uri))
            {
                this.diagnostics?.delete(document.uri);
                await this._refreshDiagnostics();
            }
        };

        const refreshFile = async uri =>
        {
            if(this._isTrackedConfiguration(uri))
            {
                this.diagnostics?.delete(uri);
                await this._refreshDiagnostics();
            }
        };

        if(vscode.workspace.onDidChangeTextDocument)
        {
            subscriptions.push(vscode.workspace.onDidChangeTextDocument(refreshDocument));
            subscriptions.push(vscode.workspace.onDidOpenTextDocument(refreshDocument));
            subscriptions.push(vscode.workspace.onDidCloseTextDocument(refreshDocument));
        }

        if(vscode.workspace.createFileSystemWatcher)
        {
            const watcher = vscode.workspace.createFileSystemWatcher('**/{*.json,.editorconfig,.clang-format,_clang-format,.eslintrc,eslint.config.*,.eslintrc.*}');
            subscriptions.push(watcher, watcher.onDidChange(refreshFile), watcher.onDidCreate(refreshFile), watcher.onDidDelete(refreshFile));
        }

        if(vscode.workspace.onDidChangeWorkspaceFolders)
        {
            subscriptions.push(vscode.workspace.onDidChangeWorkspaceFolders(refresh));
        }

        return this._refreshDiagnostics();
    },

    /** @description Disposes diagnostics together with the extension's configuration listeners. */
    dispose()
    {
        this.disposed = true;
        this.diagnostics?.dispose();
        this.trackedPaths.clear();
    },

    _isInside(root, target)
    {
        const relative = path.relative(root, target);
        return relative === '' || relative !== '..' && !relative.startsWith(`..${path.sep}`) && !path.isAbsolute(relative);
    },

    async _realPath(target)
    {
        try
        {
            return await fs.promises.realpath(target);
        }
        catch(error)
        {
            if(error.code !== 'ENOENT' && error.code !== 'ENOTDIR')
            {
                throw error;
            }

            const parent = path.dirname(target);
            if(parent === target)
            {
                throw error;
            }

            return path.join(await this._realPath(parent), path.basename(target));
        }
    },

    _isHardExcluded(sourcePath)
    {
        const segments = sourcePath.toLowerCase().split(path.sep);
        if(segments.some(segment => excludedDirectories.has(segment)))
        {
            return true;
        }

        const fixture = segments.some((segment, index) => segment === 'tests' && [ 'mocks', '__mocks__' ].includes(segments[index + 1]));
        return fixture || sourcePath.toLowerCase().endsWith('.generated.lgd') || (/\.d\.(?:ts|cts|mts)$/i).test(sourcePath);
    },

    _openDocument(configPath)
    {
        return (vscode.workspace.textDocuments || []).find(document => !document.isClosed && document.uri.scheme === 'file' && path.resolve(document.uri.fsPath) === configPath);
    },

    async _readSnapshot(configPath, context)
    {
        try
        {
            if(!this._isInside(context.workspaceRoot, configPath))
            {
                throw new Error('Extended configuration must remain inside the workspace folder.');
            }

            const realPath = await this._realPath(configPath);
            if(!this._isInside(context.realWorkspace, realPath))
            {
                throw new Error('Configuration symlinks must remain inside the workspace folder.');
            }

            let text = null;
            let document = this._openDocument(configPath);
            if(!document)
            {
                try
                {
                    const stat = await fs.promises.stat(realPath);
                    if(!stat.isFile() || stat.size > limits.bytes)
                    {
                        throw new Error('LGD configuration must be a regular file no larger than 256 KiB.');
                    }

                    text = await fs.promises.readFile(realPath, 'utf8');
                }
                catch(error)
                {
                    if(error.code !== 'ENOENT')
                    {
                        throw error;
                    }
                }

                document = this._openDocument(configPath);
            }

            let version = null;
            if(document)
            {
                text = document.getText();
                version = document.version ?? null;
            }

            if(text !== null && Buffer.byteLength(text, 'utf8') > limits.bytes)
            {
                throw new Error('LGD configuration must be no larger than 256 KiB.');
            }

            const snapshot = { path: configPath, realPath: realPath, text: text, version: version, open: Boolean(document) };
            context.snapshots.push(snapshot);
            this.diagnostics?.delete(vscode.Uri.file(configPath));
            this.trackedPaths.add(configPath);

            return snapshot;
        }
        catch(error)
        {
            error.configurationPath = configPath;
            throw error;
        }
    },

    async _load(snapshot, context)
    {
        try
        {
            if(context.stack.has(snapshot.realPath))
            {
                throw new Error('LGD configuration extends contains a cycle.');
            }

            if(context.stack.size >= limits.depth || context.snapshots.length > limits.configs)
            {
                throw new Error('LGD configuration extends exceeds the limit of 10 levels or 100 files.');
            }

            if(snapshot.text === null)
            {
                throw new Error('The extended LGD configuration file does not exist.');
            }

            const configuration = this.settings.parse(snapshot.text);
            context.stack.add(snapshot.realPath);
            const layers = [];
            let parents = configuration.extends || [];
            if(typeof parents === 'string')
            {
                parents = [parents];
            }

            for(const reference of parents)
            {
                const parentPath = path.resolve(path.dirname(snapshot.path), reference);
                const parentSnapshot = await this._readSnapshot(parentPath, context);
                layers.push(...await this._load(parentSnapshot, context));
            }

            context.stack.delete(snapshot.realPath);
            layers.push(configuration);
            return layers;
        }
        catch(error)
        {
            error.configurationPath ||= snapshot.path;
            throw error;
        }
    },

    async _resolveFormatting(result, context, sourcePath)
    {
        if(!result.formatting.enabled || result.ignored)
        {
            return;
        }

        let imported = { options: {}, rules: {}, issues: [] };
        if(result.formatting.sources.length > 0)
        {
            if(!this.formattingSources)
            {
                throw new Error('LGD formatting source reader is unavailable.');
            }

            imported = await this.formattingSources.resolve({ filePath: sourcePath, workspaceRoot: result.workspaceRoot,
                sources: result.formatting.sources, readSnapshot: filename => this._readSnapshot(filename, context) });
        }

        const resolved = LgdFormattingPolicy.resolve(result.formatting, imported, result.rules);
        result.rules = resolved.rules;
        result.formatting = resolved.formatting;
        if(imported.disabled)
        {
            result.formatting.enabled = false;
        }

        this._reportImportIssues(imported.issues || []);
    },

    _reportImportIssues(issues)
    {
        const grouped = new Map();
        for(const issue of issues)
        {
            if(!issue.path || !issue.message)
            {
                continue;
            }

            const entries = grouped.get(issue.path) || [];
            const range = new vscode.Range(new vscode.Position(0, 0), new vscode.Position(0, 1));
            const severity = issue.severity === 'error' ? vscode.DiagnosticSeverity.Error : vscode.DiagnosticSeverity.Warning;
            const diagnostic = new vscode.Diagnostic(range, issue.message, severity);
            diagnostic.source = 'LGD formatting import';
            entries.push(diagnostic);
            grouped.set(issue.path, entries);
        }

        for(const [ filename, diagnostics ] of grouped)
        {
            this.diagnostics?.set(vscode.Uri.file(filename), diagnostics);
        }
    },

    _isTrackedConfiguration(uri)
    {
        if(uri.scheme !== 'file')
        {
            return false;
        }

        const configPath = path.resolve(uri.fsPath);
        return this.trackedPaths.has(configPath) || path.basename(configPath) === 'lgd.json' && path.basename(path.dirname(configPath)) === '.vscode';
    },

    async _refreshDiagnostics()
    {
        if(this.disposed)
        {
            return;
        }

        const documents = [...vscode.workspace.textDocuments || []];
        for(const document of documents)
        {
            if(document.languageId === 'lgd')
            {
                await this.resolve(document);
            }
            else if(document.uri.scheme === 'file' && path.basename(document.uri.fsPath) === 'lgd.json' && path.basename(path.dirname(document.uri.fsPath)) === '.vscode')
            {
                const root = path.dirname(path.dirname(document.uri.fsPath));
                await this.resolve({ uri: vscode.Uri.file(path.join(root, '__lgd_configuration_check__.lgd')) });
            }
        }

        await this.onChange?.();
    },

    _reportError(configPath, message)
    {
        if(!this.diagnostics || this.disposed)
        {
            return;
        }

        const range = new vscode.Range(new vscode.Position(0, 0), new vscode.Position(0, 1));
        const diagnostic = new vscode.Diagnostic(range, message, vscode.DiagnosticSeverity.Error);
        diagnostic.source = 'LGD configuration';
        diagnostic.code = 'lgd-fix-configuration';
        this.diagnostics.set(vscode.Uri.file(configPath), [diagnostic]);
    }
};

module.exports = LgdFixConfiguration;
