name: Tests
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Jest:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '20.x'

    - name: Install Modules
      run: npm ci

    - name: Web Jest Tests
      run: npm test
